### ISSUE TITLE
How can I learn from my mistakes?

### ISSUE THREAD

**Issue by MarcusXavierr** [sibelius/ama#11]
I see that I keep repeating erros from past at work. How can I change that?

**Comment by sibelius** [comment]
What kind of mistakes? Feel free to be more specific with me sending a DM.

To learn from your mistakes, you should understand the root cause of it.
"Why" is the most important way to figure it out, the root cause.
Why did you make this mistake?
You can also document this situation and mistake in your note taking approach (like zettelkasten).
You need to reflect, and turn yourself in a more robust version of yourself.
You need to more antifragile, you need to get better when something bad happen

Try to read `Antifragile: Things That Gain from Disorder`

Try to use the `5 whys technique`

Write a public article about why did you make this mistake, and how can you avoid it in the future
